#!/bin/bash

# Markdown Site - a tool for building web sites in Markdown
# Copyright (C) 2017 Tai Kedzierski
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

### Markdown Site Generator Usage:help
#
# Tool for generating websites from markdown
#
# ENVIRONMENT VARIABLES
#
# Set the CSSDIR property to point to a directory where CSS should be pulled from
#
# Set the MDWEBDIR property to point to a directory to serve as th root of the site
#
###/doc

#%include autohelp bashout

set -u

if [[ -z "${WEBDIR+x}" ]]; then
	WEBDIR=./web.d/
fi

if [[ -z "${CSSFILE+x}" ]]; then
	CSSFILE="./markdown.css"
fi

# TODO
# allow using settings for a conf in local directory
#%include src/loadlocalconf.sh

mkdir -p "$WEBDIR"

infoe "Writing to $WEBDIR ..."

for SRCFILE in "$@"; do
	if [[ ! "$SRCFILE" =~ $(echo ".md$") ]]; then
		warne "$SRCFILE is not a Markdown file ?"
		continue
	fi
	bfname="$(basename "$SRCFILE"|sed 's/\.md$/.html/')"
	tdir="$(dirname "$SRCFILE")"
	tfile="$WEBDIR/$tdir/$bfname"

	mkdir -p "$WEBDIR/$tdir"

	if [[ -f "$CSSFILE" ]]; then
		infoe "Adding CSS from $CSSFILE"
		echo '<style>' > "$tfile"
		cat "$CSSFILE"  >> "$tfile"
		echo '</style>' >> "$tfile"
	fi
	markdown "$SRCFILE" >> "$tfile"
done
