#!/bin/bash

### Markdown Site Generator Usage:help
#
# Tool for generating websites from markdown
#
# ENVIRONMENT VARIABLES
#
# Set the CSSDIR property to point to a directory where CSS should be pulled from
#
# Set the MDWEBDIR property to point to a directory to serve as th root of the site
#
###/doc

#%include autohelp bashout

# TODO
# allow using settings for a conf in local directory

set -u

if [[ -z "${WEBDIR+x}" ]]; then
	WEBDIR=./web.d/
fi

if [[ -z "${CSSDIR+x}" ]]; then
	CSSDIR="$WEBDIR"
fi

mkdir -p "$WEBDIR"

infoe "Writing to $WEBDIR ..."

# TODO
# get basename of file

ALLFILES=
for x in "$@"; do
	tfile=$(mktemp -p ./ .previewXXXX.html)
	ALLFILES="$ALLFILES $tfile"
	if [[ "$HOME/.markdown.css" ]]; then
		echo '<style>' > "$tfile"
		cat "$HOME/.markdown.css"  >> "$tfile"
		echo '</style>' >> "$tfile"
	fi
	markdown "$x" >> "$tfile"
	# TODO
	# move to target dir using the basename
	sensible-browser $tfile 2>/dev/null >/dev/null
done

sleep 2
rm $ALLFILES
